### ISSUE TITLE
Character's nowHP

### ISSUE THREAD

**Issue by mepaling** [leemiyinghao/DoDo.io#2]
應該可以不用打英文吧..

我發現 Character Class 裡面有 maxHP
這應該不是指 nowHP 而是最大血量吧
可以放個 get function 讓我拿該玩家現在的血量嗎?
或者是有甚麼別的方法可以拿到?
我的 Game 裡面的 update() 需要用到
感謝><

**Comment by 102206502** [comment]
現在的血量是getHP()
maxHP是升等的時候看的，因為會回滿，還有自然回復的時候會看
