### ISSUE TITLE
關於 KingKill Mode

### ISSUE THREAD

**Issue by mepaling** [leemiyinghao/DoDo.io#3]
請問要怎麼拿
友方kingID & 敵方kingID 呢?
感謝><

**Comment by 102206502** [comment]
你自己記那個房間決定好的王的ID?

**Comment by mepaling** [comment]
我那邊會記一個
可是我需要知道誰被設為王
還是我應該跟server拿?
就是效法DeathMatch初始化那樣之類的?
@genesisgardian
