### ISSUE TITLE
getImage function need no parameter

### ISSUE THREAD

**Issue by leemiyinghao** [leemiyinghao/DoDo.io#4]
https://github.com/leemiyinghao/DoDo.io/blob/collideObject/src/main/java/tw/edu/ncu/softwareengineering/dodoio/CollideObject/CollideObject.java#L82-L85

@102206502, I can not provide CollideObjectManager every time I get image, this will do about list.length*30 times every second, need to be efficiency.
Pin down the image in instance of CollideObject plz.

**Comment by 102206502** [comment]
Now I set the feild in collideObjectManager
	**static** public BufferedImage[] collideObjectImages;
remove the argument in getImage
Is it OK?

**Comment by leemiyinghao** [comment]
I think static might cause some problem on your part
Did it pass unit test?

**Comment by 102206502** [comment]
還是你用
collideObjectManager.collideObjectImages[collideObject.className]
來存取圖片?
我把**static** 拿掉
我現在還想不到其他的做法
load image的方法的話，目前是有過JUnit的，測試code裡有執行到那部分，我之前就是過幾種方法，現在的這個不會出現讀取的錯誤

**Comment by mepaling** [comment]
orz 你們到底決定好了沒...
我現在把所有code都merge到我的game branch
而且也已經push上來了 (中間沒有任何conflict)
結果 Renderer.java 85行還是報錯啊
另外我發現CollideObject.java 關於getImage()那邊的function整個被註解掉了...

求解!!!!!!!!!!!! QQ
@leemiyinghao @102206502

**Comment by 102206502** [comment]
看 @leemiyinghao  覺得怎樣

**Comment by leemiyinghao** [comment]
有過JUnit就ok阿我那天不是講了

**Comment by leemiyinghao** [comment]
我只是擔心你用static會有其他問題，沒問題的話就把function parameter拔掉就好啦

**Comment by 102206502** [comment]
你說的是我的CollideObjectManagerTest?
剛剛測有過

**Comment by 102206502** [comment]
你的Rendor就不知道了

**Comment by leemiyinghao** [comment]
那就好啦，你有照界面寫就不用擔心我這邊會不會出問題

**Comment by leemiyinghao** [comment]
你把沒parameter的版本推上去就把這issue close掉吧
